global using TextCopy;
global using Microsoft.Win32;
global using Microsoft.Extensions.Logging;
global using SunamoWpf._sunamo;
global using SunamoWpf._sunamo.SunamoExceptions;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Timers;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
